# SS HK-A 1
SINGLE,60010,443,hk1.videotron.uk

# SS HK-B 2/6
SINGLE,60011,443,hk2.videotron.uk
SINGLE,60015,443,hk2.videotron.uk

# SS HK-C 3/7
SINGLE,60012,443,hk3.videotron.uk
SINGLE,60016,443,hk3.videotron.uk

# SS HK-D 4/8
SINGLE,60013,443,hk4.videotron.uk
SINGLE,60017,443,hk4.videotron.uk

# SS HK-E 5/9
SINGLE,60014,443,hk5.videotron.uk
SINGLE,60018,443,hk5.videotron.uk

# SS HK-F 10
SINGLE,60019,443,hk1.videotron.uk

# HK MED
SINGLE,62001,443,h11zk.med.videotron.uk
SINGLE,62002,443,h22zk.med.videotron.uk

# SGP-1/4
SINGLE,60030,443,sgp1.videotron.uk
SINGLE,60033,443,sgp1.videotron.uk

# SGP-2/5
SINGLE,60031,443,sgp2.videotron.uk
SINGLE,60034,443,sgp2.videotron.uk

# SGP-3/6
SINGLE,60032,443,sgp3.videotron.uk
SINGLE,60035,443,sgp3.videotron.uk

# TW-1/3/5
SINGLE,60040,443,tw1.videotron.uk
SINGLE,60042,443,tw1.videotron.uk

# TW-2/4/6
SINGLE,60041,443,tw2.videotron.uk
SINGLE,60043,443,tw2.videotron.uk

# JP-1/3
SINGLE,60050,443,jp1.videotron.uk
SINGLE,60052,443,jp1.videotron.uk

# JP-2/4
SINGLE,60051,443,jp2.videotron.uk
SINGLE,60053,443,jp2.videotron.uk

# JP-5/6
SINGLE,60054,443,jp3.videotron.uk
SINGLE,60055,443,jp3.videotron.uk

# US-A 1/4
SINGLE,60060,443,us1.videotron.uk
SINGLE,60063,443,us1.videotron.uk

# US-B 2/5
SINGLE,60061,443,us2.videotron.uk
SINGLE,60064,443,us2.videotron.uk

# US-C 3/6
SINGLE,60062,443,us3.videotron.uk
SINGLE,60065,443,us3.videotron.uk

# US-D 7/8/9/10
SINGLE,60066,443,us4.videotron.uk
SINGLE,60067,443,us5.videotron.uk
SINGLE,60068,443,us6.videotron.uk
SINGLE,60069,443,us7.videotron.uk

# ICN
SINGLE,60101,443,kr1.videotron.uk

# CDG
SINGLE,60138,443,fr1.videotron.uk

# LHR
SINGLE,60082,443,uk1.videotron.uk

# FRA
SINGLE,60125,443,fra.videotron.uk

# YUL
SINGLE,60099,443,ca.videotron.uk

# TUR
SINGLE,60140,443,tur.videotron.uk

# FN
# HK
SINGLE,51850,443,fnhka.networkspeed.info
SINGLE,51851,443,fnhka.networkspeed.info
SINGLE,51852,443,fnhka.networkspeed.info
SINGLE,51853,443,fnhka.networkspeed.info
SINGLE,51854,443,fnhka.networkspeed.info

# TW
SINGLE,51935,443,fntw1.networkspeed.info
SINGLE,51936,443,fntw1.networkspeed.info
SINGLE,51937,443,fntw1.networkspeed.info

# SGP
SINGLE,51970,443,fnsgp2.networkspeed.info
SINGLE,51971,443,fnsgp2.networkspeed.info
SINGLE,51972,443,fnsgp2.networkspeed.info

# JP
SINGLE,51925,443,fnjp2.networkspeed.info
SINGLE,51926,443,fnjp2.networkspeed.info
SINGLE,51927,443,fnjp2.networkspeed.info
SINGLE,51928,443,fnjp2.networkspeed.info

# US- 1/3/5
SINGLE,51950,443,fnus2.networkspeed.info
SINGLE,51952,443,fnus2.networkspeed.info
SINGLE,51954,443,fnus2.networkspeed.info

# US- 2/4/6
SINGLE,51951,443,fnus2.networkspeed.info
SINGLE,51953,443,fnus2.networkspeed.info
SINGLE,51955,443,fnus2.networkspeed.info

# GEM
SINGLE,51960,443,fngem.networkspeed.info
