
# SS HK-A 1
[[rules]]
type = "single"
sport = 60010
dport = 443
domain = "hk1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk1.networkspeed.info:443 ipv4"

# SS HK-B 2/6

[[rules]]
type = "single"
sport = 60010
dport = 443
domain = "hk1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk1.networkspeed.info:443 ipv6"

# SS HK-B 2/6

[[rules]]
type = "single"
sport = 60011
dport = 443
domain = "hk2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk2.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60011
dport = 443
domain = "hk2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk2.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60015
dport = 443
domain = "hk2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk2.networkspeed.info:443 ipv4"

# SS HK-C 3/7

[[rules]]
type = "single"
sport = 60015
dport = 443
domain = "hk2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk2.networkspeed.info:443 ipv6"

# SS HK-C 3/7

[[rules]]
type = "single"
sport = 60012
dport = 443
domain = "hk3.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk3.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60012
dport = 443
domain = "hk3.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk3.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60016
dport = 443
domain = "hk3.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk3.networkspeed.info:443 ipv4"

# SS HK-D 4/8

[[rules]]
type = "single"
sport = 60016
dport = 443
domain = "hk3.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk3.networkspeed.info:443 ipv6"

# SS HK-D 4/8

[[rules]]
type = "single"
sport = 60013
dport = 443
domain = "hk4.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk4.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60013
dport = 443
domain = "hk4.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk4.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60017
dport = 443
domain = "hk4.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk4.networkspeed.info:443 ipv4"

# SS HK-E 5/9

[[rules]]
type = "single"
sport = 60017
dport = 443
domain = "hk4.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk4.networkspeed.info:443 ipv6"

# SS HK-E 5/9

[[rules]]
type = "single"
sport = 60014
dport = 443
domain = "hk5.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk5.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60014
dport = 443
domain = "hk5.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk5.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60018
dport = 443
domain = "hk5.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk5.networkspeed.info:443 ipv4"

# SS HK-F 10

[[rules]]
type = "single"
sport = 60018
dport = 443
domain = "hk5.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk5.networkspeed.info:443 ipv6"

# SS HK-F 10

[[rules]]
type = "single"
sport = 60019
dport = 443
domain = "hk1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "hk1.networkspeed.info:443 ipv4"

# SGP-1/4

[[rules]]
type = "single"
sport = 60019
dport = 443
domain = "hk1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "hk1.networkspeed.info:443 ipv6"

# SGP-1/4

[[rules]]
type = "single"
sport = 60030
dport = 443
domain = "sgp1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "sgp1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60030
dport = 443
domain = "sgp1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "sgp1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60033
dport = 443
domain = "sgp1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "sgp1.networkspeed.info:443 ipv4"

# SGP-2/5

[[rules]]
type = "single"
sport = 60033
dport = 443
domain = "sgp1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "sgp1.networkspeed.info:443 ipv6"

# SGP-2/5

[[rules]]
type = "single"
sport = 60031
dport = 443
domain = "sgp2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "sgp2.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60031
dport = 443
domain = "sgp2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "sgp2.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60034
dport = 443
domain = "sgp2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "sgp2.networkspeed.info:443 ipv4"

# SGP-3/6

[[rules]]
type = "single"
sport = 60034
dport = 443
domain = "sgp2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "sgp2.networkspeed.info:443 ipv6"

# SGP-3/6

[[rules]]
type = "single"
sport = 60032
dport = 443
domain = "sgp3.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "sgp3.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60032
dport = 443
domain = "sgp3.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "sgp3.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60035
dport = 443
domain = "sgp3.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "sgp3.networkspeed.info:443 ipv4"

# TW-1/3/5

[[rules]]
type = "single"
sport = 60035
dport = 443
domain = "sgp3.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "sgp3.networkspeed.info:443 ipv6"

# TW-1/3/5

[[rules]]
type = "single"
sport = 60040
dport = 443
domain = "tw1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "tw1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60040
dport = 443
domain = "tw1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "tw1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60042
dport = 443
domain = "tw1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "tw1.networkspeed.info:443 ipv4"

# TW-2/4/6

[[rules]]
type = "single"
sport = 60042
dport = 443
domain = "tw1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "tw1.networkspeed.info:443 ipv6"

# TW-2/4/6

[[rules]]
type = "single"
sport = 60041
dport = 443
domain = "tw2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "tw2.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60041
dport = 443
domain = "tw2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "tw2.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60043
dport = 443
domain = "tw2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "tw2.networkspeed.info:443 ipv4"

# JP-1/3

[[rules]]
type = "single"
sport = 60043
dport = 443
domain = "tw2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "tw2.networkspeed.info:443 ipv6"

# JP-1/3

[[rules]]
type = "single"
sport = 60050
dport = 443
domain = "jp1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "jp1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60050
dport = 443
domain = "jp1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "jp1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60052
dport = 443
domain = "jp1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "jp1.networkspeed.info:443 ipv4"

# JP-2/4

[[rules]]
type = "single"
sport = 60052
dport = 443
domain = "jp1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "jp1.networkspeed.info:443 ipv6"

# JP-2/4

[[rules]]
type = "single"
sport = 60051
dport = 443
domain = "jp2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "jp2.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60051
dport = 443
domain = "jp2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "jp2.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60053
dport = 443
domain = "jp2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "jp2.networkspeed.info:443 ipv4"

# US-A 1/4

[[rules]]
type = "single"
sport = 60053
dport = 443
domain = "jp2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "jp2.networkspeed.info:443 ipv6"

# US-A 1/4

[[rules]]
type = "single"
sport = 60060
dport = 443
domain = "us1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60060
dport = 443
domain = "us1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60063
dport = 443
domain = "us1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us1.networkspeed.info:443 ipv4"

# US-B 2/5

[[rules]]
type = "single"
sport = 60063
dport = 443
domain = "us1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us1.networkspeed.info:443 ipv6"

# US-B 2/5

[[rules]]
type = "single"
sport = 60061
dport = 443
domain = "us2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us2.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60061
dport = 443
domain = "us2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us2.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60064
dport = 443
domain = "us2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us2.networkspeed.info:443 ipv4"

# US-C 3/6

[[rules]]
type = "single"
sport = 60064
dport = 443
domain = "us2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us2.networkspeed.info:443 ipv6"

# US-C 3/6

[[rules]]
type = "single"
sport = 60062
dport = 443
domain = "us3.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us3.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60062
dport = 443
domain = "us3.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us3.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60065
dport = 443
domain = "us3.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us3.networkspeed.info:443 ipv4"

# US-D 7/8/9

[[rules]]
type = "single"
sport = 60065
dport = 443
domain = "us3.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us3.networkspeed.info:443 ipv6"

# US-D 7/8/9

[[rules]]
type = "single"
sport = 60066
dport = 443
domain = "us4.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us4.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60066
dport = 443
domain = "us4.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us4.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60067
dport = 443
domain = "us5.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us5.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 60067
dport = 443
domain = "us5.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us5.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 60068
dport = 443
domain = "us6.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "us6.networkspeed.info:443 ipv4"

# KR

[[rules]]
type = "single"
sport = 60068
dport = 443
domain = "us6.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "us6.networkspeed.info:443 ipv6"

# KR

[[rules]]
type = "single"
sport = 60101
dport = 443
domain = "kr1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "kr1.networkspeed.info:443 ipv4"

# FR

[[rules]]
type = "single"
sport = 60101
dport = 443
domain = "kr1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "kr1.networkspeed.info:443 ipv6"

# FR

[[rules]]
type = "single"
sport = 60138
dport = 443
domain = "fr1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fr1.networkspeed.info:443 ipv4"

# UK

[[rules]]
type = "single"
sport = 60138
dport = 443
domain = "fr1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fr1.networkspeed.info:443 ipv6"

# UK

[[rules]]
type = "single"
sport = 60082
dport = 443
domain = "uk1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "uk1.networkspeed.info:443 ipv4"

# DE

[[rules]]
type = "single"
sport = 60082
dport = 443
domain = "uk1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "uk1.networkspeed.info:443 ipv6"

# DE

[[rules]]
type = "single"
sport = 60125
dport = 443
domain = "def.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "def.networkspeed.info:443 ipv4"

# MEL

[[rules]]
type = "single"
sport = 60125
dport = 443
domain = "def.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "def.networkspeed.info:443 ipv6"

# MEL

[[rules]]
type = "single"
sport = 60092
dport = 443
domain = "mel.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "mel.networkspeed.info:443 ipv4"

# CA

[[rules]]
type = "single"
sport = 60092
dport = 443
domain = "mel.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "mel.networkspeed.info:443 ipv6"

# CA

[[rules]]
type = "single"
sport = 60099
dport = 443
domain = "ca.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "ca.networkspeed.info:443 ipv4"

# FN
# HK

[[rules]]
type = "single"
sport = 60099
dport = 443
domain = "ca.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "ca.networkspeed.info:443 ipv6"

# FN
# HK

[[rules]]
type = "single"
sport = 51850
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnhka.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51850
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnhka.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51851
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnhka.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51851
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnhka.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51852
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnhka.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51852
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnhka.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51853
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnhka.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51853
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnhka.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51854
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnhka.networkspeed.info:443 ipv4"

# TW

[[rules]]
type = "single"
sport = 51854
dport = 443
domain = "fnhka.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnhka.networkspeed.info:443 ipv6"

# TW

[[rules]]
type = "single"
sport = 51935
dport = 443
domain = "fntw1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fntw1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51935
dport = 443
domain = "fntw1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fntw1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51936
dport = 443
domain = "fntw1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fntw1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51936
dport = 443
domain = "fntw1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fntw1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51937
dport = 443
domain = "fntw1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fntw1.networkspeed.info:443 ipv4"

# JP

[[rules]]
type = "single"
sport = 51937
dport = 443
domain = "fntw1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fntw1.networkspeed.info:443 ipv6"

# JP

[[rules]]
type = "single"
sport = 51925
dport = 443
domain = "fnjp1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnjp1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51925
dport = 443
domain = "fnjp1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnjp1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51926
dport = 443
domain = "fnjp2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnjp2.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51926
dport = 443
domain = "fnjp2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnjp2.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51927
dport = 443
domain = "fnjp1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnjp1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51927
dport = 443
domain = "fnjp1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnjp1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51928
dport = 443
domain = "fnjp2.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnjp2.networkspeed.info:443 ipv4"

# US

[[rules]]
type = "single"
sport = 51928
dport = 443
domain = "fnjp2.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnjp2.networkspeed.info:443 ipv6"

# US

[[rules]]
type = "single"
sport = 51950
dport = 443
domain = "fnus1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnus1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51950
dport = 443
domain = "fnus1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnus1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51951
dport = 443
domain = "fnus1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnus1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51951
dport = 443
domain = "fnus1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnus1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51952
dport = 443
domain = "fnus1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnus1.networkspeed.info:443 ipv4"


[[rules]]
type = "single"
sport = 51952
dport = 443
domain = "fnus1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnus1.networkspeed.info:443 ipv6"


[[rules]]
type = "single"
sport = 51953
dport = 443
domain = "fnus1.networkspeed.info"
protocol = "all"
ip_version = "ipv4"
comment = "fnus1.networkspeed.info:443 ipv4"

[[rules]]
type = "single"
sport = 51953
dport = 443
domain = "fnus1.networkspeed.info"
protocol = "all"
ip_version = "ipv6"
comment = "fnus1.networkspeed.info:443 ipv6"
