# HK
SINGLE,51850,443,fnhka.networkspeed.info
SINGLE,51851,443,fnhka.networkspeed.info
SINGLE,51852,443,fnhka.networkspeed.info
SINGLE,51853,443,fnhka.networkspeed.info
SINGLE,51854,443,fnhka.networkspeed.info

# TW
SINGLE,51935,443,fntw1.networkspeed.info
SINGLE,51936,443,fntw1.networkspeed.info
SINGLE,51937,443,fntw1.networkspeed.info

# SGP
SINGLE,51970,443,fnsgp2.networkspeed.info
SINGLE,51971,443,fnsgp2.networkspeed.info
SINGLE,51972,443,fnsgp2.networkspeed.info

# JP
SINGLE,51925,443,fnjp2.networkspeed.info
SINGLE,51926,443,fnjp2.networkspeed.info
SINGLE,51927,443,fnjp2.networkspeed.info
SINGLE,51928,443,fnjp2.networkspeed.info

# US- 1/3/5
SINGLE,51950,443,fnus2.networkspeed.info
SINGLE,51952,443,fnus2.networkspeed.info
SINGLE,51954,443,fnus2.networkspeed.info

# US- 2/4/6
SINGLE,51951,443,fnus2.networkspeed.info
SINGLE,51953,443,fnus2.networkspeed.info
SINGLE,51955,443,fnus2.networkspeed.info

# GEM
SINGLE,51960,443,fngem.networkspeed.info
